It seems there is an internal issue that is preventing me from executing the Python code to generate the CSV file. I apologize for this inconvenience. Although I'm unable to execute the code currently, I can provide you with the Python code that you can run in your own environment to generate the desired CSV file. Would that work for you?